// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// kernelSmoothingCovariance
arma::mat kernelSmoothingCovariance(const List& curves, const arma::vec& U, const arma::vec& V, const double& b, const double& h);
RcppExport SEXP _CovarianceEstimate_kernelSmoothingCovariance(SEXP curvesSEXP, SEXP USEXP, SEXP VSEXP, SEXP bSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelSmoothingCovariance(curves, U, V, b, h));
    return rcpp_result_gen;
END_RCPP
}
// epaKernelSmoothingCurve
arma::vec epaKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _CovarianceEstimate_epaKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(epaKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// uniKernelSmoothingCurve
arma::vec uniKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _CovarianceEstimate_uniKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(uniKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// betaKernelSmoothingCurve
arma::vec betaKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _CovarianceEstimate_betaKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(betaKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// modifiedBetaKernelSmoothingCurve
arma::vec modifiedBetaKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _CovarianceEstimate_modifiedBetaKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(modifiedBetaKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// estimateRisk
Rcpp::List estimateRisk(const List& curves, const List& curves_estim, const double& t0);
RcppExport SEXP _CovarianceEstimate_estimateRisk(SEXP curvesSEXP, SEXP curves_estimSEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< const List& >::type curves_estim(curves_estimSEXP);
    Rcpp::traits::input_parameter< const double& >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(estimateRisk(curves, curves_estim, t0));
    return rcpp_result_gen;
END_RCPP
}
// estimateRiskCurve
double estimateRiskCurve(const List& curve, const List& curve_estim);
RcppExport SEXP _CovarianceEstimate_estimateRiskCurve(SEXP curveSEXP, SEXP curve_estimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curve(curveSEXP);
    Rcpp::traits::input_parameter< const List& >::type curve_estim(curve_estimSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateRiskCurve(curve, curve_estim));
    return rcpp_result_gen;
END_RCPP
}
// estimateRiskCurves
List estimateRiskCurves(const List& curves, const List& curves_estim);
RcppExport SEXP _CovarianceEstimate_estimateRiskCurves(SEXP curvesSEXP, SEXP curves_estimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< const List& >::type curves_estim(curves_estimSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateRiskCurves(curves, curves_estim));
    return rcpp_result_gen;
END_RCPP
}
// estimateSigma
double estimateSigma(const List& curves);
RcppExport SEXP _CovarianceEstimate_estimateSigma(SEXP curvesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateSigma(curves));
    return rcpp_result_gen;
END_RCPP
}
// estimateSigmaMSE
double estimateSigmaMSE(const List& curves, const List& curves_estim);
RcppExport SEXP _CovarianceEstimate_estimateSigmaMSE(SEXP curvesSEXP, SEXP curves_estimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< const List& >::type curves_estim(curves_estimSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateSigmaMSE(curves, curves_estim));
    return rcpp_result_gen;
END_RCPP
}
// mfBm
arma::vec mfBm(arma::vec& H, arma::vec& T, int N, int K);
RcppExport SEXP _CovarianceEstimate_mfBm(SEXP HSEXP, SEXP TSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(mfBm(H, T, N, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CovarianceEstimate_kernelSmoothingCovariance", (DL_FUNC) &_CovarianceEstimate_kernelSmoothingCovariance, 5},
    {"_CovarianceEstimate_epaKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_epaKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_uniKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_uniKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_betaKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_betaKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_modifiedBetaKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_modifiedBetaKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_estimateRisk", (DL_FUNC) &_CovarianceEstimate_estimateRisk, 3},
    {"_CovarianceEstimate_estimateRiskCurve", (DL_FUNC) &_CovarianceEstimate_estimateRiskCurve, 2},
    {"_CovarianceEstimate_estimateRiskCurves", (DL_FUNC) &_CovarianceEstimate_estimateRiskCurves, 2},
    {"_CovarianceEstimate_estimateSigma", (DL_FUNC) &_CovarianceEstimate_estimateSigma, 1},
    {"_CovarianceEstimate_estimateSigmaMSE", (DL_FUNC) &_CovarianceEstimate_estimateSigmaMSE, 2},
    {"_CovarianceEstimate_mfBm", (DL_FUNC) &_CovarianceEstimate_mfBm, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CovarianceEstimate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
