// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// epaKernelSmoothingCurve
arma::vec epaKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _SmoothCurves_epaKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(epaKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// uniKernelSmoothingCurve
arma::vec uniKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _SmoothCurves_uniKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(uniKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// betaKernelSmoothingCurve
arma::vec betaKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _SmoothCurves_betaKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(betaKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// modifiedBetaKernelSmoothingCurve
arma::vec modifiedBetaKernelSmoothingCurve(const arma::vec& U, const arma::vec& T, const arma::vec& Y, const arma::vec& b);
RcppExport SEXP _SmoothCurves_modifiedBetaKernelSmoothingCurve(SEXP USEXP, SEXP TSEXP, SEXP YSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(modifiedBetaKernelSmoothingCurve(U, T, Y, b));
    return rcpp_result_gen;
END_RCPP
}
// estimateRisk
Rcpp::List estimateRisk(const List& curves, const List& curves_estim, const double& t0);
RcppExport SEXP _SmoothCurves_estimateRisk(SEXP curvesSEXP, SEXP curves_estimSEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< const List& >::type curves_estim(curves_estimSEXP);
    Rcpp::traits::input_parameter< const double& >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(estimateRisk(curves, curves_estim, t0));
    return rcpp_result_gen;
END_RCPP
}
// estimateRiskCurve
double estimateRiskCurve(const List& curve, const List& curve_estim);
RcppExport SEXP _SmoothCurves_estimateRiskCurve(SEXP curveSEXP, SEXP curve_estimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curve(curveSEXP);
    Rcpp::traits::input_parameter< const List& >::type curve_estim(curve_estimSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateRiskCurve(curve, curve_estim));
    return rcpp_result_gen;
END_RCPP
}
// estimateRiskCurves
List estimateRiskCurves(const List& curves, const List& curves_estim);
RcppExport SEXP _SmoothCurves_estimateRiskCurves(SEXP curvesSEXP, SEXP curves_estimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< const List& >::type curves_estim(curves_estimSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateRiskCurves(curves, curves_estim));
    return rcpp_result_gen;
END_RCPP
}
// estimateSigma
double estimateSigma(const List& curves);
RcppExport SEXP _SmoothCurves_estimateSigma(SEXP curvesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateSigma(curves));
    return rcpp_result_gen;
END_RCPP
}
// estimateSigmaMSE
double estimateSigmaMSE(const List& curves, const List& curves_estim);
RcppExport SEXP _SmoothCurves_estimateSigmaMSE(SEXP curvesSEXP, SEXP curves_estimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type curves(curvesSEXP);
    Rcpp::traits::input_parameter< const List& >::type curves_estim(curves_estimSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateSigmaMSE(curves, curves_estim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
<<<<<<< HEAD
    {"_CovarianceEstimate_epaKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_epaKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_uniKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_uniKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_betaKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_betaKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_modifiedBetaKernelSmoothingCurve", (DL_FUNC) &_CovarianceEstimate_modifiedBetaKernelSmoothingCurve, 4},
    {"_CovarianceEstimate_estimateRisk", (DL_FUNC) &_CovarianceEstimate_estimateRisk, 3},
    {"_CovarianceEstimate_estimateRiskCurve", (DL_FUNC) &_CovarianceEstimate_estimateRiskCurve, 2},
    {"_CovarianceEstimate_estimateRiskCurves", (DL_FUNC) &_CovarianceEstimate_estimateRiskCurves, 2},
    {"_CovarianceEstimate_estimateSigma", (DL_FUNC) &_CovarianceEstimate_estimateSigma, 1},
    {"_CovarianceEstimate_estimateSigmaMSE", (DL_FUNC) &_CovarianceEstimate_estimateSigmaMSE, 2},
=======
    {"_SmoothCurves_epaKernelSmoothingCurve", (DL_FUNC) &_SmoothCurves_epaKernelSmoothingCurve, 4},
    {"_SmoothCurves_uniKernelSmoothingCurve", (DL_FUNC) &_SmoothCurves_uniKernelSmoothingCurve, 4},
    {"_SmoothCurves_betaKernelSmoothingCurve", (DL_FUNC) &_SmoothCurves_betaKernelSmoothingCurve, 4},
    {"_SmoothCurves_modifiedBetaKernelSmoothingCurve", (DL_FUNC) &_SmoothCurves_modifiedBetaKernelSmoothingCurve, 4},
    {"_SmoothCurves_estimateRisk", (DL_FUNC) &_SmoothCurves_estimateRisk, 3},
    {"_SmoothCurves_estimateRiskCurve", (DL_FUNC) &_SmoothCurves_estimateRiskCurve, 2},
    {"_SmoothCurves_estimateRiskCurves", (DL_FUNC) &_SmoothCurves_estimateRiskCurves, 2},
    {"_SmoothCurves_estimateSigma", (DL_FUNC) &_SmoothCurves_estimateSigma, 1},
    {"_SmoothCurves_estimateSigmaMSE", (DL_FUNC) &_SmoothCurves_estimateSigmaMSE, 2},
>>>>>>> a0cefa04eac313d9c84427f165adea1e0b369ddd
    {NULL, NULL, 0}
};

RcppExport void R_init_SmoothCurves(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
