# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

epaKernelSmoothingCurve <- function(U, T, Y, b, n_obs_min) {
    .Call('_denoisr_epaKernelSmoothingCurve', PACKAGE = 'denoisr', U, T, Y, b, n_obs_min)
}

uniKernelSmoothingCurve <- function(U, T, Y, b, n_obs_min) {
    .Call('_denoisr_uniKernelSmoothingCurve', PACKAGE = 'denoisr', U, T, Y, b, n_obs_min)
}

biweightKernelSmoothingCurve <- function(U, T, Y, b, n_obs_min) {
    .Call('_denoisr_biweightKernelSmoothingCurve', PACKAGE = 'denoisr', U, T, Y, b, n_obs_min)
}

betaKernelSmoothingCurve <- function(U, T, Y, b) {
    .Call('_denoisr_betaKernelSmoothingCurve', PACKAGE = 'denoisr', U, T, Y, b)
}

modifiedBetaKernelSmoothingCurve <- function(U, T, Y, b) {
    .Call('_denoisr_modifiedBetaKernelSmoothingCurve', PACKAGE = 'denoisr', U, T, Y, b)
}

LOOmean <- function(curves, U, b, n) {
    .Call('_denoisr_LOOmean', PACKAGE = 'denoisr', curves, U, b, n)
}

mean_cpp <- function(curves, U, b) {
    .Call('_denoisr_mean_cpp', PACKAGE = 'denoisr', curves, U, b)
}

covariance_cpp <- function(curves, meanLOO_curves, sampling_points, b, h) {
    .Call('_denoisr_covariance_cpp', PACKAGE = 'denoisr', curves, meanLOO_curves, sampling_points, b, h)
}

estimateRisk <- function(curves, curves_estim, t0) {
    .Call('_denoisr_estimateRisk', PACKAGE = 'denoisr', curves, curves_estim, t0)
}

estimateRiskCurve <- function(curve, curve_estim) {
    .Call('_denoisr_estimateRiskCurve', PACKAGE = 'denoisr', curve, curve_estim)
}

estimateRiskCurves <- function(curves, curves_estim) {
    .Call('_denoisr_estimateRiskCurves', PACKAGE = 'denoisr', curves, curves_estim)
}

estimateSigma <- function(curves) {
    .Call('_denoisr_estimateSigma', PACKAGE = 'denoisr', curves)
}

estimateSigmaMSE <- function(curves, curves_estim) {
    .Call('_denoisr_estimateSigmaMSE', PACKAGE = 'denoisr', curves, curves_estim)
}

