# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernelSmoothingCovariance <- function(curves, U, V, b, h) {
    .Call('_CovarianceEstimate_kernelSmoothingCovariance', PACKAGE = 'CovarianceEstimate', curves, U, V, b, h)
}

epaKernelSmoothingCurve <- function(U, T, Y, b) {
    .Call('_CovarianceEstimate_epaKernelSmoothingCurve', PACKAGE = 'CovarianceEstimate', U, T, Y, b)
}

uniKernelSmoothingCurve <- function(U, T, Y, b) {
    .Call('_CovarianceEstimate_uniKernelSmoothingCurve', PACKAGE = 'CovarianceEstimate', U, T, Y, b)
}

betaKernelSmoothingCurve <- function(U, T, Y, b) {
    .Call('_CovarianceEstimate_betaKernelSmoothingCurve', PACKAGE = 'CovarianceEstimate', U, T, Y, b)
}

modifiedBetaKernelSmoothingCurve <- function(U, T, Y, b) {
    .Call('_CovarianceEstimate_modifiedBetaKernelSmoothingCurve', PACKAGE = 'CovarianceEstimate', U, T, Y, b)
}

estimateRisk <- function(curves, curves_estim, t0) {
    .Call('_CovarianceEstimate_estimateRisk', PACKAGE = 'CovarianceEstimate', curves, curves_estim, t0)
}

estimateRiskCurve <- function(curve, curve_estim) {
    .Call('_CovarianceEstimate_estimateRiskCurve', PACKAGE = 'CovarianceEstimate', curve, curve_estim)
}

estimateRiskCurves <- function(curves, curves_estim) {
    .Call('_CovarianceEstimate_estimateRiskCurves', PACKAGE = 'CovarianceEstimate', curves, curves_estim)
}

estimateSigma <- function(curves) {
    .Call('_CovarianceEstimate_estimateSigma', PACKAGE = 'CovarianceEstimate', curves)
}

estimateSigmaMSE <- function(curves, curves_estim) {
    .Call('_CovarianceEstimate_estimateSigmaMSE', PACKAGE = 'CovarianceEstimate', curves, curves_estim)
}

mfBm <- function(H, T, N, K) {
    .Call('_CovarianceEstimate_mfBm', PACKAGE = 'CovarianceEstimate', H, T, N, K)
}

